### ISSUE TITLE
Update npm url

### ISSUE THREAD

**Issue by o-az** [epicweb-dev/invariant#1]
Current npm url in the repo description 404s

**Comment by kentcdodds** [comment]
Which URL?

**Comment by vicainelli** [comment]
@kentcdodds 
The URL on the repository description

![image](https://github.com/epicweb-dev/invariant/assets/1155694/bcd2de63-0eae-4182-8d64-1e412bea0d6a)

**Comment by kentcdodds** [comment]
Ah! Yeah, thanks for that. I have no idea how I messed that up 😅
