### ISSUE TITLE
require() of ES Module @epic-web/invariant/dist/index.js not supported

### ISSUE THREAD

**Issue by lancejpollard** [epicweb-dev/invariant#10]
Starting to test out this library to simplify error handling of user inputs to functions, but getting this:

```
var invariant_1 = require("@epic-web/invariant");
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/myproj/node_modules/.pnpm/@epic-web+invariant@1.0.0/node_modules/@epic-web/invariant/dist/index.js from /Users/myproj/dist/node/image.js not supported.
Instead change the require of index.js in /Users/myproj/dist/node/image.js to a dynamic import() which is available in all CommonJS modules.
```

I haven't had this problem with the dozens/hundreds of node modules I've been importing into my several-layers-deep of packages. I have this system basically:

```
my-a
my-x
my-b
  import my-a
  import other-stuff
my-c
  import my-a
  import my-x
  import other-stuff
cli-tool
  import my-c
  import @epic-web/invariant
```

In the cli-tool I have `tsconfig.json` (in fact, all my projects use the same tsconfig, targeting `ES5` and `module: CommonJS`, so it works in Next.js without a transpilation step of ES6 `import/export` statements):

```json
{
  "compilerOptions": {
    "target": "ES5",
    "declaration": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "outDir": "host",
    "baseUrl": ".",
    "declarationMap": true,
    "paths": {
      "~/*": ["./*"]
    }
  },
  "include": ["code/**/*.ts", "index.ts"],
  "exclude": ["node_modules", "host"]
}
```

My `package.json` _doesn't_ include `type: module`, because that causes a whole host of other problems down the chain. My package.json has:

```
{
  "bin": {
    "my-cli": "dist/cli/index.js"
  }
}
```

Inside cli-tool, I have:

```ts
#!/usr/bin/env node

import _ from 'lodash'
import { Input, Value } from './type'
import call from '../nodejs'

call(process.argv)
```

Inside `nodejs` I import the `image` module as seen in the error, which just has:

```ts
import { invariant } from '@epic-web/invariant'

export function convert(i, o) {
  invariant(i, 'Input must be provided')
}
```

I compile "watch" with:

```
concurrently --kill-others "tsc -w" "tsc-alias -w"
```

That builds to the `./dist/cli/index.js` directory and all the rest of the TS files. They look like this (i.e. **ES5** CommonJS modules):

```js
#!/usr/bin/env node
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var lodash_1 = __importDefault(require("lodash"));
var task = __importStar(require("./task"));
call(process.argv);
```

I landed on this approach after months of banging my head on the wall with ES6 not `import` not working in various configurations. If I change my `tsconfig.json` to be `module: 2015` or later, I get:

```
import _ from 'lodash';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Then that takes me down the road of changing the `package.json` to `type: module`. But that doesn't work in Next.js or the browser... So I'm unsure what's best here.

What should we do here? What should _I_ do?

Can you somehow add support to your lib for this?

Can I somehow cross-compile it so I don't have to change my main tsconfig across projects?

What is the best approach?

Thank you for your help!

StackOverflow isn't of much use :) https://stackoverflow.com/questions/69081410/error-err-require-esm-require-of-es-module-not-supported

**P.S.** I would like for this lib to work in node.js and the browser, importing it in future libraries, so hopefully we can land on a solution that supports that.

**Comment by lancejpollard** [comment]
It can be worked around with the tmp hack for today:

```ts
const { invariant } = await eval(`import('@epic-web/invariant')`)
```

**Comment by kentcdodds** [comment]
Hi @lancejpollard,

I only plan on supporting native ESM. Every modern environment I target supports ESM. If you can't run ESM, then you can use a dynamic import:

```ts
const { invariant } = await import('@epic-web/invariant')
```

If that doesn't work for you then I suggest copying the library into your project :)

It's tiny: https://github.com/epicweb-dev/invariant/blob/main/src/index.ts

Cheers!
