### ISSUE TITLE
Feat: ability to return response

### ISSUE THREAD

**Issue by otatar** [epicweb-dev/invariant#5]
Hi there,

I think it would be useful if we could return response, not just throw it. For example when validating a form on server (action in Remix) we usually return response with errors if any, so we can render errors in form. `invariantResponse` throws response and it is caught by `ErrorBoundary`. Maybe `invariantReturnResponse` function...?

**Comment by kentcdodds** [comment]
Thanks, but that's out of scope for this library. For those kinds of errors you should use [conform](https://conform.guid) + [zod](https://zod.dev).
